# Generated by Django 2.2.7 on 2019-11-23 05:29

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('Menu', models.TextField(blank=True)),
                ('Total', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('latlng', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('meta', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='chicken',
            old_name='content',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='chicken',
            name='image',
            field=models.ImageField(default='default_image.PNG', upload_to=''),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('amount', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('meta', jsonfield.fields.JSONField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chickens.Shop')),
            ],
        ),
    ]
