# Generated by Django 2.2.7 on 2019-11-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chickens', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('shop', 'name')},
        ),
    ]
