# Generated by Django 2.2.7 on 2019-11-24 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='rate',
        ),
    ]
