# Generated by Django 2.2.7 on 2019-11-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('chickenID', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
    ]
